/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roombooking;

import java.awt.FlowLayout;
import java.awt.List;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static roombooking.Guipage5.Deserialize;

/**
 *
 * @author ovais
 */
public class Guipage4 extends javax.swing.JFrame {

    /**
     * Creates new form Guipage4
     */
    public Guipage4() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impress BT", 0, 36)); // NOI18N
        jLabel2.setText("Admin Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 10, 210, 40);

        jButton1.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton1.setText("Display SeminarRoom Timetable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 110, 250, 40);

        jLabel3.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel3.setText("Press to Create new Admin");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 270, 230, 40);

        jButton2.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton2.setText("Check Notifications");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 170, 160, 40);

        jLabel5.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jLabel5.setText("Press to Add a new Class");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 220, 170, 40);

        jButton3.setFont(new java.awt.Font("Impress BT", 0, 24)); // NOI18N
        jButton3.setText("Book!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 370, 150, 40);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 320, 100, 30);

        jButton4.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(410, 370, 120, 30);

        jButton5.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton5.setText("Create Admin");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(350, 270, 160, 40);

        jLabel7.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel7.setText("Press to check Notifications");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 170, 230, 40);

        jButton6.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton6.setText("Add a Class");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(350, 220, 160, 40);

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(10, 320, 100, 30);

        jTextField3.setText(" ");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(240, 320, 100, 30);

        jButton7.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton7.setText("Display BreakoutRoom Timetable");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(250, 60, 260, 40);

        jButton8.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton8.setText("Display ClassRoom Timetable");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(10, 60, 230, 40);

        jLabel4.setText("Enter Class Name        Enter  Day                Enter Slot Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 300, 360, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rtlstudent\\Documents\\NetBeansProjects\\RoomBooking\\src\\roombooking\\polygonal-texture-background-vector.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Guipage7 abc=new Guipage7();
        abc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    this.dispose();
    Guipage1 abc= new Guipage1();
    abc.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList SR=Deserialize("SR");
        Jtable ab=new Jtable();
        ab.start(SR, "SR");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       ArrayList BR=Deserialize("BR");
       Jtable ab=new Jtable();
        ab.start(BR, "BR");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       ArrayList CR=Deserialize("CR");
       Jtable ab=new Jtable();
        ab.start(CR, "CR");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        Guipage6 abc= new Guipage6();
        abc.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   
        try{  String a=jTextField2.getText();
       String b=jTextField1.getText();
       int ab=0 ;
      if(b.equalsIgnoreCase("monday"))
           ab=0;
      if(b.equalsIgnoreCase("tuesday"))
           ab=1;
      if(b.equalsIgnoreCase("wednesday"))
          ab=2;
      if(b.equalsIgnoreCase("thursday"))
          ab=3;
      if(b.equalsIgnoreCase("Friday"))
          ab=4;
      if(b.equalsIgnoreCase("Saturday"))
          ab=5;
      
       int c=Integer.parseInt(jTextField3.getText())-1;
       if(a.startsWith("C", 2)||a.startsWith("c", 2)){
        ArrayList abc=Deserialize("CR");
           for (int i = 0; i < abc.size(); i++) {
               ClassRoom ba=(ClassRoom)abc.get(i);
               if(a.equalsIgnoreCase(ba.getname())){
                   if(ba.TimeTableArr[c][ab]==false){
                       JOptionPane.showMessageDialog(null,
                    "Room already Booked",
                    "Please Select Another",
                    JOptionPane.ERROR_MESSAGE);
                       break;}
                   else{abc.remove(i);
                       ba.TimeTableArr[c][ab]=false;
                   JOptionPane.showMessageDialog(null,
                    "Successfully booked",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                   abc.add(ba);
                         FileOutputStream fileOut2;
                       try {
                           fileOut2 = new FileOutputStream("CR.dat",false);
                           ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                            out2.writeObject(abc);
                            out2.close();
                       } catch (FileNotFoundException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       } catch (IOException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       }
     
                   break;}}
              if(i==abc.size()-1){
                   JOptionPane.showMessageDialog(null,
                    "You have entered Something wrong",
                    "Please Try again",
                    JOptionPane.ERROR_MESSAGE);
               }}}
       if(a.startsWith("S", 2)||a.startsWith("s", 2)){
        ArrayList abc=Deserialize("SR");
           for (int i = 0; i < abc.size(); i++) {
               SeminarRoom ba=(SeminarRoom)abc.get(i);
               if(a.equalsIgnoreCase(ba.getname())){
                   if(ba.TimeTableArr[c][ab]==false){
                       JOptionPane.showMessageDialog(null,
                    "Room already Booked",
                    "Please Select Another",
                    JOptionPane.ERROR_MESSAGE);
                       break;}
                   else{abc.remove(i);
                       ba.TimeTableArr[c][ab]=false;
                   JOptionPane.showMessageDialog(null,
                    "Successfully booked",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                   abc.add(ba);
                         FileOutputStream fileOut2;
                       try {
                           fileOut2 = new FileOutputStream("SR.dat",false);
                           ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                            out2.writeObject(abc);
                            out2.close();
                       } catch (FileNotFoundException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       } catch (IOException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       }
                   break;}}
              if(i==abc.size()-1){
                   JOptionPane.showMessageDialog(null,
                    "You have entered Something wrong",
                    "Please Try again",
                    JOptionPane.ERROR_MESSAGE);
               }}}
       if(a.startsWith("B", 0)||a.startsWith("b", 0)){
        ArrayList abc=Deserialize("BR");
           for (int i = 0; i < abc.size(); i++) {
               Breakout ba=(Breakout)abc.get(i);
               if(a.equalsIgnoreCase(ba.getname())){
                   if(ba.TimeTableArr[c][ab]==false){
                       JOptionPane.showMessageDialog(null,
                    "Room already Booked",
                    "Please Select Another",
                    JOptionPane.ERROR_MESSAGE);
                       break;}
                   else{abc.remove(i);
                       ba.TimeTableArr[c][ab]=false;
                   JOptionPane.showMessageDialog(null,
                    "Successfully booked",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                   abc.add(ba);
                         FileOutputStream fileOut2;
                       try {
                           fileOut2 = new FileOutputStream("BR.dat",false);
                           ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                            out2.writeObject(abc);
                            out2.close();
                       } catch (FileNotFoundException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       } catch (IOException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       }
                   break;}}
              if(i==abc.size()-1){
                   JOptionPane.showMessageDialog(null,
                    "You have entered Something wrong",
                    "Please Try again",
                    JOptionPane.ERROR_MESSAGE);
               }}}}
    catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null,
                   "Please Enter something in the fields ",
                    "Please Try again",
                    JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       ArrayList ab= Deserialize("admin");
       Admin ac= new Admin();
       String name = JOptionPane.showInputDialog(null, "Name Of Admin");
       ac.setname(name);
       String Id = JOptionPane.showInputDialog(null, "Enter Id for Admin");
       ac.setID(Id);
       String pass = JOptionPane.showInputDialog(null, "Enter Password for Admin");
       ac.setPass(pass);
       ab.add(ac);
       FileOutputStream fileOut2;
            try {
                fileOut2 = new FileOutputStream("admin.dat",false);
                ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                out2.writeObject(ab);
                out2.close();
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Guipage6.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Guipage6.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
         jTextField3.setText("");
    }//GEN-LAST:event_jTextField3MouseClicked
    public static ArrayList Deserialize(String a ){
    ArrayList Room = null;
    String s=a+".dat";
    try {
        ObjectInputStream in = new ObjectInputStream(new FileInputStream(s));
        Room = (ArrayList)in.readObject(); 
        in.close();
    }
    catch(Exception e) {}
    return Room;
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Guipage4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Guipage4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Guipage4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Guipage4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Guipage4().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
