/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roombooking;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ovais
 */
public class Guipage6 extends javax.swing.JFrame {

    /**
     * Creates new form Guipage
     */
    public Guipage6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        c = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impress BT", 0, 36)); // NOI18N
        jLabel2.setText("Add New Class");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 10, 260, 40);

        jLabel6.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel6.setText("Projector (only for Seminar or ClassRoom):");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 200, 370, 40);

        jLabel7.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel7.setText("Name Of Class:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 50, 130, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(300, 60, 240, 20);

        jLabel8.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel8.setText("Location (Building):");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 90, 160, 40);

        jLabel9.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel9.setText("Capacity:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 120, 160, 40);

        a.setText("Seminar Room");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a);
        a.setBounds(170, 170, 110, 23);

        b.setText("Class Room");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b);
        b.setBounds(301, 170, 110, 23);

        c.setText("Break Out Room");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c);
        c.setBounds(420, 170, 120, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tabba", "Adamjee", "CED" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(420, 100, 120, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(420, 210, 120, 20);

        jLabel10.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel10.setText("Type Of Class:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 160, 160, 40);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "40", "60" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(420, 130, 120, 20);

        jLabel11.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel11.setText("Wednesday");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(240, 240, 100, 40);

        jLabel12.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel12.setText("Tuesday");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(160, 240, 70, 40);

        jLabel13.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel13.setText("(Tick means Vacant)");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(230, 460, 170, 40);

        jLabel14.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel14.setText("Thursday");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(340, 240, 90, 40);

        jLabel15.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel15.setText("Monday");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(90, 240, 70, 40);

        jLabel16.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel16.setText("Friday");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(420, 240, 50, 40);

        jLabel17.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel17.setText("4th Slot");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 350, 70, 50);

        jLabel18.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel18.setText("6th Slot");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 420, 80, 40);

        jLabel19.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel19.setText("2nd Slot");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 300, 80, 40);

        jLabel20.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel20.setText("5th Slot");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 390, 80, 40);

        jLabel21.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel21.setText("3rd Slot");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 330, 80, 40);

        jLabel22.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel22.setText("Saturday");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(480, 240, 80, 40);
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(110, 280, 20, 21);
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(270, 280, 20, 21);
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(360, 280, 20, 21);
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(440, 280, 20, 21);
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(500, 280, 20, 21);
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(110, 310, 20, 21);
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(180, 310, 20, 21);
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(270, 310, 20, 21);
        jPanel1.add(jCheckBox9);
        jCheckBox9.setBounds(360, 310, 20, 21);
        jPanel1.add(jCheckBox10);
        jCheckBox10.setBounds(440, 310, 20, 21);
        jPanel1.add(jCheckBox11);
        jCheckBox11.setBounds(500, 310, 20, 21);
        jPanel1.add(jCheckBox12);
        jCheckBox12.setBounds(110, 340, 20, 21);
        jPanel1.add(jCheckBox13);
        jCheckBox13.setBounds(180, 340, 20, 21);
        jPanel1.add(jCheckBox14);
        jCheckBox14.setBounds(270, 340, 20, 21);
        jPanel1.add(jCheckBox15);
        jCheckBox15.setBounds(360, 340, 20, 21);
        jPanel1.add(jCheckBox16);
        jCheckBox16.setBounds(440, 340, 20, 21);
        jPanel1.add(jCheckBox17);
        jCheckBox17.setBounds(500, 340, 20, 21);
        jPanel1.add(jCheckBox18);
        jCheckBox18.setBounds(110, 370, 20, 21);
        jPanel1.add(jCheckBox19);
        jCheckBox19.setBounds(180, 370, 20, 21);
        jPanel1.add(jCheckBox20);
        jCheckBox20.setBounds(270, 370, 20, 21);
        jPanel1.add(jCheckBox21);
        jCheckBox21.setBounds(360, 370, 20, 21);
        jPanel1.add(jCheckBox22);
        jCheckBox22.setBounds(440, 370, 20, 21);
        jPanel1.add(jCheckBox23);
        jCheckBox23.setBounds(500, 370, 20, 21);
        jPanel1.add(jCheckBox24);
        jCheckBox24.setBounds(110, 400, 20, 21);
        jPanel1.add(jCheckBox25);
        jCheckBox25.setBounds(180, 400, 20, 21);
        jPanel1.add(jCheckBox26);
        jCheckBox26.setBounds(270, 400, 20, 21);
        jPanel1.add(jCheckBox27);
        jCheckBox27.setBounds(360, 400, 20, 21);
        jPanel1.add(jCheckBox28);
        jCheckBox28.setBounds(440, 400, 20, 21);
        jPanel1.add(jCheckBox29);
        jCheckBox29.setBounds(500, 400, 20, 21);
        jPanel1.add(jCheckBox30);
        jCheckBox30.setBounds(110, 430, 20, 21);
        jPanel1.add(jCheckBox31);
        jCheckBox31.setBounds(180, 430, 20, 21);
        jPanel1.add(jCheckBox32);
        jCheckBox32.setBounds(270, 430, 20, 21);
        jPanel1.add(jCheckBox33);
        jCheckBox33.setBounds(360, 430, 20, 21);
        jPanel1.add(jCheckBox34);
        jCheckBox34.setBounds(440, 430, 20, 21);
        jPanel1.add(jCheckBox35);
        jCheckBox35.setBounds(500, 430, 20, 21);
        jPanel1.add(jCheckBox36);
        jCheckBox36.setBounds(180, 280, 20, 21);

        jButton1.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 460, 140, 33);

        jButton2.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jButton2.setText("Create Class");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(423, 460, 140, 33);

        jLabel23.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jLabel23.setText("1st Slot");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(10, 270, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rtlstudent\\Documents\\NetBeansProjects\\RoomBooking\\src\\roombooking\\polygonal-texture-background-vector.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Guipage4 abc= new Guipage4();
        abc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
     if(a.isSelected()){
         b.setSelected(false);
         c.setSelected(false);
     }
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        if(b.isSelected()){
         a.setSelected(false);
         c.setSelected(false);
     }
    }//GEN-LAST:event_bActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        if(c.isSelected()){
         b.setSelected(false);
         a.setSelected(false);
     }
    }//GEN-LAST:event_cActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(a.isSelected()){
            SeminarRoom abc=new SeminarRoom();
            abc.setname(jTextField2.getText());
            if(jComboBox1.getSelectedIndex()==0){
                abc.setbuilding("Tabba");
            }
            else if(jComboBox1.getSelectedIndex()==1){
                abc.setbuilding("Adamjee");
            }
            else if (jComboBox1.getSelectedIndex()==2){
                abc.setbuilding("CED");
            }
            if(jComboBox3.getSelectedIndex()==0){
                abc.setCapacity(10);
            }
            else if(jComboBox3.getSelectedIndex()==1){
                abc.setCapacity(40);
            }
            else if(jComboBox3.getSelectedIndex()==2){
                abc.setCapacity(60);
            }
            if(jComboBox2.getSelectedIndex()==0){
                abc.setprojector(true);
            }
            else if (jComboBox2.getSelectedIndex()==1){
                abc.setprojector(false);
            }
            abc.intTT();
           
                if(jCheckBox1.isSelected())
                    abc.TimeTableArr[0][0]=true;
                else
                    abc.TimeTableArr[0][0]=false;
                 if(jCheckBox36.isSelected())
                    abc.TimeTableArr[0][1]=true;
                else
                    abc.TimeTableArr[0][1]=false;
                 if(jCheckBox2.isSelected())
                    abc.TimeTableArr[0][2]=true;
                else
                    abc.TimeTableArr[0][2]=false;
                 if(jCheckBox3.isSelected())
                    abc.TimeTableArr[0][3]=true;
                else
                    abc.TimeTableArr[0][3]=false;
                 if(jCheckBox4.isSelected())
                    abc.TimeTableArr[0][4]=true;
                else
                    abc.TimeTableArr[0][4]=false;
                 if(jCheckBox5.isSelected())
                    abc.TimeTableArr[0][5]=true;
                else
                    abc.TimeTableArr[0][5]=false;
                 if(jCheckBox6.isSelected())
                    abc.TimeTableArr[1][0]=true;
                else
                    abc.TimeTableArr[1][0]=false;
                if(jCheckBox7.isSelected())
                    abc.TimeTableArr[1][1]=true;
                else
                    abc.TimeTableArr[1][1]=false;
                if(jCheckBox8.isSelected())
                    abc.TimeTableArr[1][2]=true;
                else
                    abc.TimeTableArr[1][2]=false;
               if(jCheckBox9.isSelected())
                    abc.TimeTableArr[1][3]=true;
                else
                    abc.TimeTableArr[1][3]=false;
               if(jCheckBox10.isSelected())
                    abc.TimeTableArr[1][4]=true;
                else
                    abc.TimeTableArr[1][4]=false;
               if(jCheckBox11.isSelected())
                    abc.TimeTableArr[1][5]=true;
                else
                    abc.TimeTableArr[1][5]=false;
               if(jCheckBox12.isSelected())
                    abc.TimeTableArr[2][0]=true;
                else
                    abc.TimeTableArr[2][0]=false;
               if(jCheckBox13.isSelected())
                    abc.TimeTableArr[2][1]=true;
                else
                    abc.TimeTableArr[2][1]=false;
               if(jCheckBox14.isSelected())
                    abc.TimeTableArr[2][2]=true;
                else
                    abc.TimeTableArr[2][2]=false;
               if(jCheckBox15.isSelected())
                    abc.TimeTableArr[2][3]=true;
                else
                    abc.TimeTableArr[2][3]=false;
               if(jCheckBox16.isSelected())
                    abc.TimeTableArr[2][4]=true;
                else
                    abc.TimeTableArr[2][4]=false;
               if(jCheckBox17.isSelected())
                    abc.TimeTableArr[2][5]=true;
                else
                    abc.TimeTableArr[2][5]=false;
               if(jCheckBox18.isSelected())
                    abc.TimeTableArr[3][0]=true;
                else
                    abc.TimeTableArr[3][0]=false;
               if(jCheckBox19.isSelected())
                    abc.TimeTableArr[3][1]=true;
                else
                    abc.TimeTableArr[3][1]=false;
               if(jCheckBox20.isSelected())
                    abc.TimeTableArr[3][2]=true;
                else
                    abc.TimeTableArr[3][2]=false;
               if(jCheckBox21.isSelected())
                    abc.TimeTableArr[3][3]=true;
                else
                    abc.TimeTableArr[3][3]=false;
               if(jCheckBox22.isSelected())
                    abc.TimeTableArr[3][4]=true;
                else
                    abc.TimeTableArr[3][4]=false;
               if(jCheckBox23.isSelected())
                    abc.TimeTableArr[3][5]=true;
                else
                    abc.TimeTableArr[3][5]=false;
               if(jCheckBox24.isSelected())
                    abc.TimeTableArr[4][0]=true;
                else
                    abc.TimeTableArr[4][0]=false;
                if(jCheckBox25.isSelected())
                    abc.TimeTableArr[4][1]=true;
                else
                    abc.TimeTableArr[4][1]=false;
                if(jCheckBox26.isSelected())
                    abc.TimeTableArr[4][2]=true;
                else
                    abc.TimeTableArr[4][2]=false;
                if(jCheckBox27.isSelected())
                    abc.TimeTableArr[4][3]=true;
                else
                    abc.TimeTableArr[4][3]=false;
                if(jCheckBox28.isSelected())
                    abc.TimeTableArr[4][4]=true;
                else
                    abc.TimeTableArr[4][4]=false;
                if(jCheckBox29.isSelected())
                    abc.TimeTableArr[4][5]=true;
                else
                    abc.TimeTableArr[4][5]=false;
                if(jCheckBox30.isSelected())
                    abc.TimeTableArr[5][0]=true;
                else
                    abc.TimeTableArr[5][0]=false;
                if(jCheckBox31.isSelected())
                    abc.TimeTableArr[5][1]=true;
                else
                    abc.TimeTableArr[5][1]=false;
                if(jCheckBox32.isSelected())
                    abc.TimeTableArr[5][2]=true;
                else
                    abc.TimeTableArr[5][2]=false;
                if(jCheckBox33.isSelected())
                    abc.TimeTableArr[5][3]=true;
                else
                    abc.TimeTableArr[5][3]=false;
                if(jCheckBox34.isSelected())
                    abc.TimeTableArr[5][4]=true;
                else
                    abc.TimeTableArr[5][4]=false;
                    if(jCheckBox35.isSelected())
                    abc.TimeTableArr[5][5]=true;
                else
                    abc.TimeTableArr[5][5]=false;
            ArrayList SR=Deserialize("SR");
            SR.add(abc);
            
            
                  FileOutputStream fileOut2;
            try {
                fileOut2 = new FileOutputStream("SR.dat",false);
                ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                out2.writeObject(SR);
                out2.close();
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Guipage6.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Guipage6.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
        if(b.isSelected()){
            ClassRoom abc=new ClassRoom();
            abc.setname(jTextField2.getText());
            if(jComboBox1.getSelectedIndex()==0){
                abc.setbuilding("Tabba");
            }
            else if(jComboBox1.getSelectedIndex()==1){
                abc.setbuilding("Adamjee");
            }
            else if (jComboBox1.getSelectedIndex()==2){
                abc.setbuilding("CED");
            }
            if(jComboBox3.getSelectedIndex()==0){
                abc.setCapacity(10);
            }
            else if(jComboBox3.getSelectedIndex()==1){
                abc.setCapacity(40);
            }
            else if(jComboBox3.getSelectedIndex()==2){
                abc.setCapacity(60);
            }
            if(jComboBox2.getSelectedIndex()==0){
                abc.setprojector(true);
            }
            else if (jComboBox2.getSelectedIndex()==1){
                abc.setprojector(false);
            }
            abc.intTT();
            
                if(jCheckBox1.isSelected())
                    abc.TimeTableArr[0][0]=true;
                else
                    abc.TimeTableArr[0][0]=false;
                 if(jCheckBox36.isSelected())
                    abc.TimeTableArr[0][1]=true;
                else
                    abc.TimeTableArr[0][1]=false;
                 if(jCheckBox2.isSelected())
                    abc.TimeTableArr[0][2]=true;
                else
                    abc.TimeTableArr[0][2]=false;
                 if(jCheckBox3.isSelected())
                    abc.TimeTableArr[0][3]=true;
                else
                    abc.TimeTableArr[0][3]=false;
                 if(jCheckBox4.isSelected())
                    abc.TimeTableArr[0][4]=true;
                else
                    abc.TimeTableArr[0][4]=false;
                 if(jCheckBox5.isSelected())
                    abc.TimeTableArr[0][5]=true;
                else
                    abc.TimeTableArr[0][5]=false;
                 if(jCheckBox6.isSelected())
                    abc.TimeTableArr[1][0]=true;
                else
                    abc.TimeTableArr[1][0]=false;
                if(jCheckBox7.isSelected())
                    abc.TimeTableArr[1][1]=true;
                else
                    abc.TimeTableArr[1][1]=false;
                if(jCheckBox8.isSelected())
                    abc.TimeTableArr[1][2]=true;
                else
                    abc.TimeTableArr[1][2]=false;
               if(jCheckBox9.isSelected())
                    abc.TimeTableArr[1][3]=true;
                else
                    abc.TimeTableArr[1][3]=false;
               if(jCheckBox10.isSelected())
                    abc.TimeTableArr[1][4]=true;
                else
                    abc.TimeTableArr[1][4]=false;
               if(jCheckBox11.isSelected())
                    abc.TimeTableArr[1][5]=true;
                else
                    abc.TimeTableArr[1][5]=false;
               if(jCheckBox12.isSelected())
                    abc.TimeTableArr[2][0]=true;
                else
                    abc.TimeTableArr[2][0]=false;
               if(jCheckBox13.isSelected())
                    abc.TimeTableArr[2][1]=true;
                else
                    abc.TimeTableArr[2][1]=false;
               if(jCheckBox14.isSelected())
                    abc.TimeTableArr[2][2]=true;
                else
                    abc.TimeTableArr[2][2]=false;
               if(jCheckBox15.isSelected())
                    abc.TimeTableArr[2][3]=true;
                else
                    abc.TimeTableArr[2][3]=false;
               if(jCheckBox16.isSelected())
                    abc.TimeTableArr[2][4]=true;
                else
                    abc.TimeTableArr[2][4]=false;
               if(jCheckBox17.isSelected())
                    abc.TimeTableArr[2][5]=true;
                else
                    abc.TimeTableArr[2][5]=false;
               if(jCheckBox18.isSelected())
                    abc.TimeTableArr[3][0]=true;
                else
                    abc.TimeTableArr[3][0]=false;
               if(jCheckBox19.isSelected())
                    abc.TimeTableArr[3][1]=true;
                else
                    abc.TimeTableArr[3][1]=false;
               if(jCheckBox20.isSelected())
                    abc.TimeTableArr[3][2]=true;
                else
                    abc.TimeTableArr[3][2]=false;
               if(jCheckBox21.isSelected())
                    abc.TimeTableArr[3][3]=true;
                else
                    abc.TimeTableArr[3][3]=false;
               if(jCheckBox22.isSelected())
                    abc.TimeTableArr[3][4]=true;
                else
                    abc.TimeTableArr[3][4]=false;
               if(jCheckBox23.isSelected())
                    abc.TimeTableArr[3][5]=true;
                else
                    abc.TimeTableArr[3][5]=false;
               if(jCheckBox24.isSelected())
                    abc.TimeTableArr[4][0]=true;
                else
                    abc.TimeTableArr[4][0]=false;
                if(jCheckBox25.isSelected())
                    abc.TimeTableArr[4][1]=true;
                else
                    abc.TimeTableArr[4][1]=false;
                if(jCheckBox26.isSelected())
                    abc.TimeTableArr[4][2]=true;
                else
                    abc.TimeTableArr[4][2]=false;
                if(jCheckBox27.isSelected())
                    abc.TimeTableArr[4][3]=true;
                else
                    abc.TimeTableArr[4][3]=false;
                if(jCheckBox28.isSelected())
                    abc.TimeTableArr[4][4]=true;
                else
                    abc.TimeTableArr[4][4]=false;
                if(jCheckBox29.isSelected())
                    abc.TimeTableArr[4][5]=true;
                else
                    abc.TimeTableArr[4][5]=false;
                if(jCheckBox30.isSelected())
                    abc.TimeTableArr[5][0]=true;
                else
                    abc.TimeTableArr[5][0]=false;
                if(jCheckBox31.isSelected())
                    abc.TimeTableArr[5][1]=true;
                else
                    abc.TimeTableArr[5][1]=false;
                if(jCheckBox32.isSelected())
                    abc.TimeTableArr[5][2]=true;
                else
                    abc.TimeTableArr[5][2]=false;
                if(jCheckBox33.isSelected())
                    abc.TimeTableArr[5][3]=true;
                else
                    abc.TimeTableArr[5][3]=false;
                if(jCheckBox34.isSelected())
                    abc.TimeTableArr[5][4]=true;
                else
                    abc.TimeTableArr[5][4]=false;
                    if(jCheckBox35.isSelected())
                    abc.TimeTableArr[5][5]=true;
                else
                    abc.TimeTableArr[5][5]=false;
            ArrayList SR=Deserialize("CR");
            SR.add(abc);
            
            
                  FileOutputStream fileOut2;
            try {
                fileOut2 = new FileOutputStream("CR.dat",false);
                ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                out2.writeObject(SR);
                out2.close();
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Guipage6.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Guipage6.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
        if(c.isSelected()){
            Breakout abc=new Breakout();
            abc.setname(jTextField2.getText());
            if(jComboBox1.getSelectedIndex()==0){
                abc.setbuilding("Tabba");
            }
            else if(jComboBox1.getSelectedIndex()==1){
                abc.setbuilding("Adamjee");
            }
            else if (jComboBox1.getSelectedIndex()==2){
                abc.setbuilding("CED");
            }
            if(jComboBox3.getSelectedIndex()==0){
                abc.setCapacity(10);
            }
            else if(jComboBox3.getSelectedIndex()==1){
                abc.setCapacity(40);
            }
            else if(jComboBox3.getSelectedIndex()==2){
                abc.setCapacity(60);
            }
            
            abc.intTT();
            
                if(jCheckBox1.isSelected())
                    abc.TimeTableArr[0][0]=true;
                else
                    abc.TimeTableArr[0][0]=false;
                 if(jCheckBox36.isSelected())
                    abc.TimeTableArr[0][1]=true;
                else
                    abc.TimeTableArr[0][1]=false;
                 if(jCheckBox2.isSelected())
                    abc.TimeTableArr[0][2]=true;
                else
                    abc.TimeTableArr[0][2]=false;
                 if(jCheckBox3.isSelected())
                    abc.TimeTableArr[0][3]=true;
                else
                    abc.TimeTableArr[0][3]=false;
                 if(jCheckBox4.isSelected())
                    abc.TimeTableArr[0][4]=true;
                else
                    abc.TimeTableArr[0][4]=false;
                 if(jCheckBox5.isSelected())
                    abc.TimeTableArr[0][5]=true;
                else
                    abc.TimeTableArr[0][5]=false;
                 if(jCheckBox6.isSelected())
                    abc.TimeTableArr[1][0]=true;
                else
                    abc.TimeTableArr[1][0]=false;
                if(jCheckBox7.isSelected())
                    abc.TimeTableArr[1][1]=true;
                else
                    abc.TimeTableArr[1][1]=false;
                if(jCheckBox8.isSelected())
                    abc.TimeTableArr[1][2]=true;
                else
                    abc.TimeTableArr[1][2]=false;
               if(jCheckBox9.isSelected())
                    abc.TimeTableArr[1][3]=true;
                else
                    abc.TimeTableArr[1][3]=false;
               if(jCheckBox10.isSelected())
                    abc.TimeTableArr[1][4]=true;
                else
                    abc.TimeTableArr[1][4]=false;
               if(jCheckBox11.isSelected())
                    abc.TimeTableArr[1][5]=true;
                else
                    abc.TimeTableArr[1][5]=false;
               if(jCheckBox12.isSelected())
                    abc.TimeTableArr[2][0]=true;
                else
                    abc.TimeTableArr[2][0]=false;
               if(jCheckBox13.isSelected())
                    abc.TimeTableArr[2][1]=true;
                else
                    abc.TimeTableArr[2][1]=false;
               if(jCheckBox14.isSelected())
                    abc.TimeTableArr[2][2]=true;
                else
                    abc.TimeTableArr[2][2]=false;
               if(jCheckBox15.isSelected())
                    abc.TimeTableArr[2][3]=true;
                else
                    abc.TimeTableArr[2][3]=false;
               if(jCheckBox16.isSelected())
                    abc.TimeTableArr[2][4]=true;
                else
                    abc.TimeTableArr[2][4]=false;
               if(jCheckBox17.isSelected())
                    abc.TimeTableArr[2][5]=true;
                else
                    abc.TimeTableArr[2][5]=false;
               if(jCheckBox18.isSelected())
                    abc.TimeTableArr[3][0]=true;
                else
                    abc.TimeTableArr[3][0]=false;
               if(jCheckBox19.isSelected())
                    abc.TimeTableArr[3][1]=true;
                else
                    abc.TimeTableArr[3][1]=false;
               if(jCheckBox20.isSelected())
                    abc.TimeTableArr[3][2]=true;
                else
                    abc.TimeTableArr[3][2]=false;
               if(jCheckBox21.isSelected())
                    abc.TimeTableArr[3][3]=true;
                else
                    abc.TimeTableArr[3][3]=false;
               if(jCheckBox22.isSelected())
                    abc.TimeTableArr[3][4]=true;
                else
                    abc.TimeTableArr[3][4]=false;
               if(jCheckBox23.isSelected())
                    abc.TimeTableArr[3][5]=true;
                else
                    abc.TimeTableArr[3][5]=false;
               if(jCheckBox24.isSelected())
                    abc.TimeTableArr[4][0]=true;
                else
                    abc.TimeTableArr[4][0]=false;
                if(jCheckBox25.isSelected())
                    abc.TimeTableArr[4][1]=true;
                else
                    abc.TimeTableArr[4][1]=false;
                if(jCheckBox26.isSelected())
                    abc.TimeTableArr[4][2]=true;
                else
                    abc.TimeTableArr[4][2]=false;
                if(jCheckBox27.isSelected())
                    abc.TimeTableArr[4][3]=true;
                else
                    abc.TimeTableArr[4][3]=false;
                if(jCheckBox28.isSelected())
                    abc.TimeTableArr[4][4]=true;
                else
                    abc.TimeTableArr[4][4]=false;
                if(jCheckBox29.isSelected())
                    abc.TimeTableArr[4][5]=true;
                else
                    abc.TimeTableArr[4][5]=false;
                if(jCheckBox30.isSelected())
                    abc.TimeTableArr[5][0]=true;
                else
                    abc.TimeTableArr[5][0]=false;
                if(jCheckBox31.isSelected())
                    abc.TimeTableArr[5][1]=true;
                else
                    abc.TimeTableArr[5][1]=false;
                if(jCheckBox32.isSelected())
                    abc.TimeTableArr[5][2]=true;
                else
                    abc.TimeTableArr[5][2]=false;
                if(jCheckBox33.isSelected())
                    abc.TimeTableArr[5][3]=true;
                else
                    abc.TimeTableArr[5][3]=false;
                if(jCheckBox34.isSelected())
                    abc.TimeTableArr[5][4]=true;
                else
                    abc.TimeTableArr[5][4]=false;
                    if(jCheckBox35.isSelected())
                    abc.TimeTableArr[5][5]=true;
                else
                    abc.TimeTableArr[5][5]=false;
            ArrayList SR=Deserialize("BR");
            SR.add(abc);
            
            
                  FileOutputStream fileOut2;
            try {
                fileOut2 = new FileOutputStream("BR.dat",false);
                ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                out2.writeObject(SR);
                out2.close();
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Guipage6.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Guipage6.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
        JOptionPane.showMessageDialog(null,
                    "Class Successfully Created",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        Guipage4 abc=new Guipage4();
        abc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
public static ArrayList Deserialize(String a ){
    ArrayList abc = null;
    String s=a+".dat";
    try {
        ObjectInputStream in = new ObjectInputStream(new FileInputStream(s));
        abc = (ArrayList)in.readObject(); 
        in.close();
    }
    catch(Exception e) {}
    return abc;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guipage6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guipage6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guipage6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guipage6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guipage6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton b;
    private javax.swing.JRadioButton c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
