/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roombooking;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static roombooking.Guipage4.Deserialize;

/**
 *
 * @author ovais
 */
public class Guipage5 extends javax.swing.JFrame {

    /**
     * Creates new form Guipage5
     */
    public Guipage5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Impress BT", 0, 36)); // NOI18N
        jLabel2.setText("Student Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 10, 240, 40);

        jButton3.setFont(new java.awt.Font("Impress BT", 0, 24)); // NOI18N
        jButton3.setText("Book!");
        jButton3.setToolTipText("");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(180, 290, 150, 40);

        jButton4.setFont(new java.awt.Font("Impress BT", 0, 18)); // NOI18N
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(350, 320, 120, 30);

        jButton8.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton8.setText("Display ClassRoom Timetable");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(10, 90, 230, 40);

        jButton7.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton7.setText("Display Breakout Timetable");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(260, 90, 220, 40);

        jButton1.setFont(new java.awt.Font("Impress BT", 0, 14)); // NOI18N
        jButton1.setText("Display SeminarRoom Timetable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 140, 250, 40);

        jTextField2.setToolTipText("Try to Write Exact Name in Caps");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField2MouseEntered(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(10, 230, 100, 30);

        jTextField3.setToolTipText("Enter in LowerCase Only");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(130, 230, 100, 30);

        jTextField4.setToolTipText("Enter Slot Number Only");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField4MouseEntered(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(240, 230, 100, 30);

        jLabel3.setText("Enter Class Name               Enter  Day                Enter Slot Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 200, 330, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rtlstudent\\Documents\\NetBeansProjects\\RoomBooking\\src\\roombooking\\polygonal-texture-background-vector.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        Guipage1 abc= new Guipage1();
        abc.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ArrayList CR=Deserialize("CR");
        Jtable ab=new Jtable();
        ab.start(CR, "CR");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ArrayList BR=Deserialize("BR");
        Jtable ab=new Jtable();
        ab.start(BR, "BR");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList SR=Deserialize("SR");
        Jtable ab=new Jtable();
        ab.start(SR, "SR");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try{  String a=jTextField2.getText();
       String b=jTextField3.getText();
       int ab = 0;
      if(b.equalsIgnoreCase("monday"))
           ab=0;
      if(b.equalsIgnoreCase("tuesday"))
           ab=1;
      if(b.equalsIgnoreCase("wednesday"))
          ab=2;
      if(b.equalsIgnoreCase("thursday"))
          ab=3;
      if(b.equalsIgnoreCase("Friday"))
          ab=4;
      if(b.equalsIgnoreCase("Saturday"))
          ab=5;
      
       int c=Integer.parseInt(jTextField4.getText())-1;
      if(a.startsWith("C", 2)||a.startsWith("c", 2)){
        ArrayList abc=Deserialize("CR");
           for (int i = 0; i < abc.size(); i++) {
               ClassRoom ba=(ClassRoom)abc.get(i);
               if(a.equalsIgnoreCase(ba.getname())){
                   if(ba.TimeTableArr[c][ab]==false){
                       JOptionPane.showMessageDialog(null,
                    "Room already Booked",
                    "Please Select Another",
                    JOptionPane.ERROR_MESSAGE);
                       break;}
                   else{
                   
                   Request demo=new Request();
                   demo.setname(ba.getname());
                   demo.setday(ab);
                   demo.setslot(c+1);
                   ArrayList asd=Deserialize("request");
                   asd.add(demo);
                         FileOutputStream fileOut2;
                       try {
                           fileOut2 = new FileOutputStream("request.dat",false);
                           ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                            out2.writeObject(asd);
                            out2.close();
                       } catch (FileNotFoundException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       } catch (IOException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       }
                    JOptionPane.showMessageDialog(null,
                    "Request For Booking has Been made. Keep checking Timetable to see for Approval",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                   break;}}
              if(i==abc.size()-1){
                   JOptionPane.showMessageDialog(null,
                    "You have entered Something wrong",
                    "Please Try again",
                    JOptionPane.ERROR_MESSAGE);
               }}}
      if(a.startsWith("S", 2)||a.startsWith("s", 2)){
        ArrayList abc=Deserialize("SR");
           for (int i = 0; i < abc.size(); i++) {
               SeminarRoom ba=(SeminarRoom)abc.get(i);
               if(a.equalsIgnoreCase(ba.getname())){
                   if(ba.TimeTableArr[c][ab]==false){
                       JOptionPane.showMessageDialog(null,
                    "Room already Booked",
                    "Please Select Another",
                    JOptionPane.ERROR_MESSAGE);
                       break;}
                   else{
                   
                   Request demo=new Request();
                   demo.setname(ba.getname());
                   demo.setday(ab);
                   demo.setslot(c+1);
                   ArrayList asd=Deserialize("request");
                   asd.add(demo);
                         FileOutputStream fileOut2;
                       try {
                           fileOut2 = new FileOutputStream("request.dat",false);
                           ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                            out2.writeObject(asd);
                            out2.close();
                       } catch (FileNotFoundException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       } catch (IOException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       }
                    JOptionPane.showMessageDialog(null,
                    "Request For Booking has Been made. Keep checking Timetable to see for Approval",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                   break;}}
              if(i==abc.size()-1){
                   JOptionPane.showMessageDialog(null,
                    "You have entered Something wrong",
                    "Please Try again",
                    JOptionPane.ERROR_MESSAGE);
               }}}
      if(a.startsWith("B", 0)||a.startsWith("b", 0)){
        ArrayList abc=Deserialize("SR");
           for (int i = 0; i < abc.size(); i++) {
               Breakout ba=(Breakout)abc.get(i);
               if(a.equalsIgnoreCase(ba.getname())){
                   if(ba.TimeTableArr[c][ab]==false){
                       JOptionPane.showMessageDialog(null,
                    "Room already Booked",
                    "Please Select Another",
                    JOptionPane.ERROR_MESSAGE);
                       break;}
                   else{
                   
                   Request demo=new Request();
                   demo.setname(ba.getname());
                   demo.setday(ab);
                   demo.setslot(c+1);
                   ArrayList asd=Deserialize("request");
                   asd.add(demo);
                         FileOutputStream fileOut2;
                       try {
                           fileOut2 = new FileOutputStream("request.dat",false);
                           ObjectOutputStream out2 = new ObjectOutputStream(fileOut2);
                            out2.writeObject(asd);
                            out2.close();
                       } catch (FileNotFoundException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       } catch (IOException ex) {
                           Logger.getLogger(Guipage4.class.getName()).log(Level.SEVERE, null, ex);
                       }
                    JOptionPane.showMessageDialog(null,
                    "Request For Booking has Been made. Keep checking Timetable to see for Approval",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                   break;}}
              if(i==abc.size()-1){
                   JOptionPane.showMessageDialog(null,
                    "You have entered Something wrong",
                    "Please Try again",
                    JOptionPane.ERROR_MESSAGE);
               }}}}
     catch(Exception e){
         JOptionPane.showMessageDialog(null,
                    "Please Enter something in the fields ",
                    "Please Try again",
                    JOptionPane.ERROR_MESSAGE);
     }
      
               
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseEntered
        
    }//GEN-LAST:event_jTextField2MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        
    }//GEN-LAST:event_jButton3MouseEntered

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseEntered
        
    }//GEN-LAST:event_jTextField4MouseEntered

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
       jTextField4.setText("");
    }//GEN-LAST:event_jTextField4MouseClicked
public static ArrayList Deserialize(String a ){
    ArrayList Room = null;
    String s=a+".dat";
    try {
        ObjectInputStream in = new ObjectInputStream(new FileInputStream(s));
        Room = (ArrayList)in.readObject(); 
        in.close();
    }
    catch(Exception e) {}
    return Room;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guipage5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guipage5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guipage5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guipage5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guipage5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
